name: Run Azure Login
on:
  push:
    branches:
      - test

permissions:
  id-token: write
  contents: read
jobs:
  demo:
    runs-on: ubuntu-latest
    environment: Azure
    steps:
      - name: "Azure PowerShell login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          auth-type: SERVICE_PRINCIPAL # NOTE: It's a UAMI used above!

      - name: "Get resource groups"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Get-AzResourceGroup
          azPSVersion: "latest"
